### ISSUE TITLE
How to achieve the count(distinct ) function in SQL

### ISSUE THREAD

**Issue by chenzhaohangbj12** [srikalyc/Sql4D#91]
I would like to use the "count(distinct )" query, but not found in the wiki,Slq4d  Whether or not support this function？
thank you~

**Comment by srikalyc** [comment]
See posts in this blog http://druidwithsql.tumblr.com/ . Search for UNIQUE

**Comment by chenzhaohangbj12** [comment]
Why the result is  “11.029647221949576”
Maybe “11” is what I want.

**Comment by srikalyc** [comment]
Thats because of approximation algorithm druid uses. You can trim it to integral value on client side.

**Comment by chenzhaohangbj12** [comment]
thank you!
